force-app/main/default/objects/Sub_To_Do__c/Sub_To_Do__c.object-meta.xml
<CustomObject>
    <label>Sub To-Do</label>
    <nameField>
        <label>Sub To-Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub To-Dos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_To_Do__c/fields/To_Do__c.field-meta.xml
<CustomField>
    <fullName>To_Do__c</fullName>
    <label>To-Do</label>
    <referenceTo>To_Do__c</referenceTo>
    <relationshipLabel>Sub To-Dos</relationshipLabel>
    <relationshipName>Sub_To_Dos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>To-Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

final/force-app/main/default/classes/SubToDoTriggerTest.cls
@IsTest
private class SubToDoTriggerTest {
      @IsTest
      static void afterInsertTest() {
        Test.setMock(HttpCalloutMock.class, new SubToDoRESTClientMock());
        Sub_To_Do__c subToDo = new Sub_To_Do__c(Name = 'test');
        To_Do__c toDo = new To_Do__c(Name = 'test');
        Test.startTest();
        insert(toDo);
        subToDo.To_Do__c = toDo.Id;
        insert (subToDo);
        Test.stopTest();
        
        Sub_To_Do__c resultSubToDo = [
          SELECT Id, External_Id__c
          FROM Sub_To_Do__c
          WHERE Name = 'test'
          LIMIT 1
        ];
        System.assert(resultSubToDo!=null);
        System.assert(resultSubToDo.External_Id__c != '');
      }
      @IsTest
      static void afterUpdateTest() {
        Test.setMock(HttpCalloutMock.class, new SubToDoRESTClientMock());
        To_Do__c toDo = new To_Do__c(Name = 'test');
        Sub_To_Do__c subToDo = new Sub_To_Do__c(Name = 'test');
        Test.startTest();
        insert(toDo);
        subToDo.To_Do__c = toDo.Id;
        insert (subToDo);
        subToDo.Description__c = 'test description';
        update (subToDo);
        Test.stopTest();
        Sub_To_Do__c resultSubToDo = [
          SELECT Id, External_Id__c,Description__c
          FROM Sub_To_Do__c
          WHERE Name = 'test'
          LIMIT 1
        ];
        System.assertEquals(
            'test description',
          resultSubToDo.Description__c
        );
      }
      @IsTest
      static void afterDeleteTest() {
        Test.setMock(HttpCalloutMock.class, new SubToDoRESTClientMock());
        To_Do__c toDo = new To_Do__c(Name = 'test');
        Sub_To_Do__c subToDo = new Sub_To_Do__c(Name = 'test');
        Test.startTest();
        insert(toDo);
        subToDo.To_Do__c = toDo.Id;
        insert (subToDo);
        delete (subToDo);
        Test.stopTest();
      List<Sub_To_Do__c> resultSubToDo = [
          SELECT Id, External_Id__c,Description__c
          FROM Sub_To_Do__c
          WHERE Name = 'test'
        ];
        System.assert(resultSubToDo.isEmpty());
    }
    
}