force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>To-Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date of creation To-Do record.</description>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Ended- Successful</fullName>
            </value>
            <value>
                <fullName>Ended- Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanOldTodosBatchTest.cls
@IsTest
private class CleanOldTodosBatchTest {
    
    static final Integer BATCH_SIZE = 200;
    static final Integer MONTHS = 3;
    static final Date CREATED_DATE = Date.today().addMonths(-(MONTHS + 1));
    static final String TODO_NAME = 'TestToDo';
    static final String STATUS = 'Ended-Succesful';
 
    @testSetup static void setup(){
        
        List<To_Do__c> testTodos = new List<To_Do__c>();
        for (Integer i = 0; i < BATCH_SIZE; i++) {
            To_Do__c oldTodo = new To_Do__c(Name = TODO_NAME + i, 
                                            Created_Date__c = CREATED_DATE,
                                            Status__c = STATUS);
            testTodos.add(oldTodo);
        }
        insert testTodos;
    }
    
    @IsTest static void testCleanOldTodos() {
		
        List<To_Do__c> todos = [SELECT Id FROM To_Do__c]; 
        System.assertEquals(BATCH_SIZE, todos.size());
        
        List<Id> ids = new List<Id>();
        for (To_Do__c todo : todos) {
            ids.add(todo.Id);
        }
        System.assertEquals(todos.size(), ids.size());
         
        Test.startTest();
        String query = 'SELECT Id FROM To_Do__c WHERE Created_Date__c < LAST_N_MONTHS:' + MONTHS + ' AND Status__c = \'' + STATUS + '\'';
		CleanOldTodosBatch batch = new CleanOldTodosBatch(query); 
		Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(0, [SELECT COUNT() FROM To_Do__c]);    
    }
}