force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>To-Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date of creation To-Do record.</description>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CleanOldTodosTest.cls
@IsTest
private class CleanOldTodosBatchTest {
    
    @IsTest static void testCleanOldTodos() {
		
        // We can test only one execution that's why we create 200 Todo
        List<To_Do__c> todos = TestDataFactory.createOldTodos(200);    
        List<Id> ids = new List<Id>();
        for (To_Do__c todo : todos) {
            ids.add(todo.Id);
        }
        System.assertEquals(ids.size(), 200);

        Test.startTest();
        String query = 'SELECT Id, Created_Date__c from To_Do__c';
		CleanOldTodosBatch batch = new CleanOldTodosBatch(query); 
		Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(0, [SELECT COUNT() FROM To_Do__c]);    
    }
}