force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>To-Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date of creation To-Do record.</description>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
    
    public static List<To_Do__c> createOldTodos(Integer numberOfTodos) {
        
        List<To_Do__c> testTodos = new List<To_Do__c>();
        Date created = Date.today().addMonths(-4);
        for (Integer i = 0; i < numberOfTodos; i++) {
            To_Do__c oldTodo = new To_Do__c(Name = 'TestToDo' + i, Created_Date__c = created);
            testTodos.add(oldTodo);
        }
        insert testTodos;
        return testTodos;
    }
}