force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>To-Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date of creation To-Do record.</description>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Ended- Successful</fullName>
            </value>
            <value>
                <fullName>Ended- Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanOldTodosScheduler.cls
public class CleanOldTodosScheduler implements Schedulable {
     
	static final String STATUS_1 = 'Ended- Successful';
    static final String STATUS_2 = 'Ended- Unsuccessful';
       
    public Integer numberOfMonths;
    
    {
        List<Clean_Old_To_Dos_Config__mdt> config = [SELECT Number_Of_Months__c FROM Clean_Old_To_Dos_Config__mdt];
        numberOfMonths = Integer.valueOf(config.get(0).Number_Of_Months__c);    
    } 
    
    public void execute(SchedulableContext context){
        
        //'SELECT Id FROM To_Do__c WHERE Created_Date__c < LAST_N_MONTHS:' + MONTHS + ' AND Status__c = \'' + STATUS + '\'';
        String query = 'SELECT Id FROM To_Do__c WHERE Created_Date__c < LAST_N_MONTHS:' + numberOfMonths + 
            ' AND (Status__c = \'' + STATUS_1 + '\' OR Status__c = \'' + STATUS_2 + '\')' ;
		CleanOldTodosBatch batch = new CleanOldTodosBatch(query); 
		Database.executeBatch(batch);        
    }
}